<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

#### **Exercise 1**

| Term       | Brief description                                                                                       |
|------------|---------------------------------------------------------------------------------------------------------|
| Subsetting | means to 'select' (from a list, array, dictionary in Python)                                            |
| Indexing   | means to retrieve the element at a specific position or 'index'                                         |
| Slicing    | means to retrieve a range of elements between specific position                                         |
| Masking    | allows us to convert numpy arrays into an array of true/false, allowing us to see only the true subset. |

#### **Exercise 2**

In [7]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
#1
subset=(np_array_2d[0::,0]).astype(int)
print(subset)

#2
subset=subset%2
print(subset)

#3
mask=subset==1
print(mask)

#4
for i in range(len(mask)):
    if mask[i]:
        print(np_array_2d[i][1])

[ 1  3  2  4  5  7  6  8 10  9]
[1 1 0 0 1 1 0 0 0 1]
[ True  True False False  True  True False False False  True]
A
C
E
G
I


#### **Exercise 3**

In [ ]:
arr = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

arr[arr < 50] = -1
arr[arr == 50] = 0
arr[arr > 50] = 1

print(arr)


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
